# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          environment-file: environment.yml
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Lint with flake8
        shell: pwsh
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        shell: pwsh
        run: |
          pytest tests/
